### PR TITLE
Update table.py - added 'size' paramter

### PR DESCRIPTION
**Pull request by galra**
Added 'size' parameter to the get_rows method. This enables to retrieve more than 100 rows in a request. Otherwise, a maximum of 100 rows is returned by default.
For tables hosted by baserow (rather then self-hosted, which can be configured), there's a limit of 200 rows.

### CODE REVIEW

**Comment by jimwitte** [comment]
Thank you for the pull request. I’ve reviewed the changes and have some suggestions for improvement.

The original code incorrectly uses “page_size” when building the request URL; it should use “size” instead. In other words, “size” and “page_size” are intended to perform the same function.

There should also be tests for the “size” parameter. The PR submitted here introduces a new parameter “size” but leaves the original, non-functional “page_size” intact.

A better solution would be to change all instances of “page_size” to “size”. This might be as simple as a search and replace operation. Additionally, the documentation should be updated to reflect this change.

I can make these changes if you prefer. Please let me know how you’d like to proceed.

**Comment by galra** [comment]
Hi Jim,

Thanks for the feedback!
I'm away from a computer at the moment, probably for a few days.
I'll check when I'm back if the task is still open. Feel free to fix it
yourself in the meanwhile, I don't mind about the contribution record etc.

Best,
Gal

**Comment by galra** [comment]
Hi Jim,

I believe both issues are solved now. Please let me know if I'm mistaken.

Best,
Gal

**Comment by galra** [comment]
Hi again,

I found a bug in the mechanism of fetching further pages in RowsIterator (actually, I didn't realize this mechanism is there until now because of the bug). It seems to work fine now. Please let me know if there's an issue.

Best,
Gal

**Comment by jimwitte** [comment]
I've completed fixes for the errors you identified, thanks for your help! Revised version 0.1.0b2 is available on pypi.

I'll work on adding the autonumber and password field types next. Should involve adding classes to the baserowapi/models/field.py file.

**Comment by galra** [comment]
I'm excited to use the pypi version.
I saw that these types required a bit more work than first anticipated, and
didn't go down the rabbit hole.

Thanks Jim!

**Pull request closed without merging**
